//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace insurance.B_Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class insurance_entities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“insurance_entities”部分中的连接字符串初始化新 insurance_entities 对象。
        /// </summary>
        public insurance_entities() : base("name=insurance_entities", "insurance_entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 insurance_entities 对象。
        /// </summary>
        public insurance_entities(string connectionString) : base(connectionString, "insurance_entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 insurance_entities 对象。
        /// </summary>
        public insurance_entities(EntityConnection connection) : base(connection, "insurance_entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<cases> cases
        {
            get
            {
                if ((_cases == null))
                {
                    _cases = base.CreateObjectSet<cases>("cases");
                }
                return _cases;
            }
        }
        private ObjectSet<cases> _cases;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<field_range> field_range
        {
            get
            {
                if ((_field_range == null))
                {
                    _field_range = base.CreateObjectSet<field_range>("field_range");
                }
                return _field_range;
            }
        }
        private ObjectSet<field_range> _field_range;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<investigation> investigation
        {
            get
            {
                if ((_investigation == null))
                {
                    _investigation = base.CreateObjectSet<investigation>("investigation");
                }
                return _investigation;
            }
        }
        private ObjectSet<investigation> _investigation;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<lgn> lgn
        {
            get
            {
                if ((_lgn == null))
                {
                    _lgn = base.CreateObjectSet<lgn>("lgn");
                }
                return _lgn;
            }
        }
        private ObjectSet<lgn> _lgn;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<modify_color> modify_color
        {
            get
            {
                if ((_modify_color == null))
                {
                    _modify_color = base.CreateObjectSet<modify_color>("modify_color");
                }
                return _modify_color;
            }
        }
        private ObjectSet<modify_color> _modify_color;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 cases EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocases(cases cases)
        {
            base.AddObject("cases", cases);
        }
    
        /// <summary>
        /// 用于向 field_range EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTofield_range(field_range field_range)
        {
            base.AddObject("field_range", field_range);
        }
    
        /// <summary>
        /// 用于向 investigation EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToinvestigation(investigation investigation)
        {
            base.AddObject("investigation", investigation);
        }
    
        /// <summary>
        /// 用于向 lgn EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTolgn(lgn lgn)
        {
            base.AddObject("lgn", lgn);
        }
    
        /// <summary>
        /// 用于向 modify_color EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomodify_color(modify_color modify_color)
        {
            base.AddObject("modify_color", modify_color);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="B_Models", Name="cases")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cases : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 cases 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="cid">cid 属性的初始值。</param>
        public static cases Createcases(global::System.Int32 id, global::System.Int64 cid)
        {
            cases cases = new cases();
            cases.id = id;
            cases.cid = cid;
            return cases;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 cid
        {
            get
            {
                return _cid;
            }
            set
            {
                OncidChanging(value);
                ReportPropertyChanging("cid");
                _cid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cid");
                OncidChanged();
            }
        }
        private global::System.Int64 _cid;
        partial void OncidChanging(global::System.Int64 value);
        partial void OncidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> current_state
        {
            get
            {
                return _current_state;
            }
            set
            {
                Oncurrent_stateChanging(value);
                ReportPropertyChanging("current_state");
                _current_state = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("current_state");
                Oncurrent_stateChanged();
            }
        }
        private Nullable<global::System.Int32> _current_state;
        partial void Oncurrent_stateChanging(Nullable<global::System.Int32> value);
        partial void Oncurrent_stateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_reported
        {
            get
            {
                return _is_reported;
            }
            set
            {
                Onis_reportedChanging(value);
                ReportPropertyChanging("is_reported");
                _is_reported = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_reported");
                Onis_reportedChanged();
            }
        }
        private Nullable<global::System.Int32> _is_reported;
        partial void Onis_reportedChanging(Nullable<global::System.Int32> value);
        partial void Onis_reportedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_submit
        {
            get
            {
                return _is_submit;
            }
            set
            {
                Onis_submitChanging(value);
                ReportPropertyChanging("is_submit");
                _is_submit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_submit");
                Onis_submitChanged();
            }
        }
        private Nullable<global::System.Int32> _is_submit;
        partial void Onis_submitChanging(Nullable<global::System.Int32> value);
        partial void Onis_submitChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_investigate
        {
            get
            {
                return _is_investigate;
            }
            set
            {
                Onis_investigateChanging(value);
                ReportPropertyChanging("is_investigate");
                _is_investigate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_investigate");
                Onis_investigateChanged();
            }
        }
        private Nullable<global::System.Int32> _is_investigate;
        partial void Onis_investigateChanging(Nullable<global::System.Int32> value);
        partial void Onis_investigateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_data_holonomic
        {
            get
            {
                return _is_data_holonomic;
            }
            set
            {
                Onis_data_holonomicChanging(value);
                ReportPropertyChanging("is_data_holonomic");
                _is_data_holonomic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_data_holonomic");
                Onis_data_holonomicChanged();
            }
        }
        private Nullable<global::System.Int32> _is_data_holonomic;
        partial void Onis_data_holonomicChanging(Nullable<global::System.Int32> value);
        partial void Onis_data_holonomicChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String data_remark
        {
            get
            {
                return _data_remark;
            }
            set
            {
                Ondata_remarkChanging(value);
                ReportPropertyChanging("data_remark");
                _data_remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("data_remark");
                Ondata_remarkChanged();
            }
        }
        private global::System.String _data_remark;
        partial void Ondata_remarkChanging(global::System.String value);
        partial void Ondata_remarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_informed
        {
            get
            {
                return _is_informed;
            }
            set
            {
                Onis_informedChanging(value);
                ReportPropertyChanging("is_informed");
                _is_informed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_informed");
                Onis_informedChanged();
            }
        }
        private Nullable<global::System.Int32> _is_informed;
        partial void Onis_informedChanging(Nullable<global::System.Int32> value);
        partial void Onis_informedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_diffcult
        {
            get
            {
                return _is_diffcult;
            }
            set
            {
                Onis_diffcultChanging(value);
                ReportPropertyChanging("is_diffcult");
                _is_diffcult = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_diffcult");
                Onis_diffcultChanged();
            }
        }
        private Nullable<global::System.Int32> _is_diffcult;
        partial void Onis_diffcultChanging(Nullable<global::System.Int32> value);
        partial void Onis_diffcultChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String diffcult_reason
        {
            get
            {
                return _diffcult_reason;
            }
            set
            {
                Ondiffcult_reasonChanging(value);
                ReportPropertyChanging("diffcult_reason");
                _diffcult_reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("diffcult_reason");
                Ondiffcult_reasonChanged();
            }
        }
        private global::System.String _diffcult_reason;
        partial void Ondiffcult_reasonChanging(global::System.String value);
        partial void Ondiffcult_reasonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String report_type
        {
            get
            {
                return _report_type;
            }
            set
            {
                Onreport_typeChanging(value);
                ReportPropertyChanging("report_type");
                _report_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("report_type");
                Onreport_typeChanged();
            }
        }
        private global::System.String _report_type;
        partial void Onreport_typeChanging(global::System.String value);
        partial void Onreport_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> report_time
        {
            get
            {
                return _report_time;
            }
            set
            {
                Onreport_timeChanging(value);
                ReportPropertyChanging("report_time");
                _report_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("report_time");
                Onreport_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _report_time;
        partial void Onreport_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onreport_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String report_phone
        {
            get
            {
                return _report_phone;
            }
            set
            {
                Onreport_phoneChanging(value);
                ReportPropertyChanging("report_phone");
                _report_phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("report_phone");
                Onreport_phoneChanged();
            }
        }
        private global::System.String _report_phone;
        partial void Onreport_phoneChanging(global::System.String value);
        partial void Onreport_phoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String application_id
        {
            get
            {
                return _application_id;
            }
            set
            {
                Onapplication_idChanging(value);
                ReportPropertyChanging("application_id");
                _application_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("application_id");
                Onapplication_idChanged();
            }
        }
        private global::System.String _application_id;
        partial void Onapplication_idChanging(global::System.String value);
        partial void Onapplication_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String policy_id
        {
            get
            {
                return _policy_id;
            }
            set
            {
                Onpolicy_idChanging(value);
                ReportPropertyChanging("policy_id");
                _policy_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("policy_id");
                Onpolicy_idChanged();
            }
        }
        private global::System.String _policy_id;
        partial void Onpolicy_idChanging(global::System.String value);
        partial void Onpolicy_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String policy_type
        {
            get
            {
                return _policy_type;
            }
            set
            {
                Onpolicy_typeChanging(value);
                ReportPropertyChanging("policy_type");
                _policy_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("policy_type");
                Onpolicy_typeChanged();
            }
        }
        private global::System.String _policy_type;
        partial void Onpolicy_typeChanging(global::System.String value);
        partial void Onpolicy_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String policy_holder
        {
            get
            {
                return _policy_holder;
            }
            set
            {
                Onpolicy_holderChanging(value);
                ReportPropertyChanging("policy_holder");
                _policy_holder = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("policy_holder");
                Onpolicy_holderChanged();
            }
        }
        private global::System.String _policy_holder;
        partial void Onpolicy_holderChanging(global::System.String value);
        partial void Onpolicy_holderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String insurant_name
        {
            get
            {
                return _insurant_name;
            }
            set
            {
                Oninsurant_nameChanging(value);
                ReportPropertyChanging("insurant_name");
                _insurant_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("insurant_name");
                Oninsurant_nameChanged();
            }
        }
        private global::System.String _insurant_name;
        partial void Oninsurant_nameChanging(global::System.String value);
        partial void Oninsurant_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String insurant_sex
        {
            get
            {
                return _insurant_sex;
            }
            set
            {
                Oninsurant_sexChanging(value);
                ReportPropertyChanging("insurant_sex");
                _insurant_sex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("insurant_sex");
                Oninsurant_sexChanged();
            }
        }
        private global::System.String _insurant_sex;
        partial void Oninsurant_sexChanging(global::System.String value);
        partial void Oninsurant_sexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String insurant_habitation
        {
            get
            {
                return _insurant_habitation;
            }
            set
            {
                Oninsurant_habitationChanging(value);
                ReportPropertyChanging("insurant_habitation");
                _insurant_habitation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("insurant_habitation");
                Oninsurant_habitationChanged();
            }
        }
        private global::System.String _insurant_habitation;
        partial void Oninsurant_habitationChanging(global::System.String value);
        partial void Oninsurant_habitationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String insurant_idcard
        {
            get
            {
                return _insurant_idcard;
            }
            set
            {
                Oninsurant_idcardChanging(value);
                ReportPropertyChanging("insurant_idcard");
                _insurant_idcard = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("insurant_idcard");
                Oninsurant_idcardChanged();
            }
        }
        private global::System.String _insurant_idcard;
        partial void Oninsurant_idcardChanging(global::System.String value);
        partial void Oninsurant_idcardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> insurant_age
        {
            get
            {
                return _insurant_age;
            }
            set
            {
                Oninsurant_ageChanging(value);
                ReportPropertyChanging("insurant_age");
                _insurant_age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("insurant_age");
                Oninsurant_ageChanged();
            }
        }
        private Nullable<global::System.Int32> _insurant_age;
        partial void Oninsurant_ageChanging(Nullable<global::System.Int32> value);
        partial void Oninsurant_ageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String insurant_phone
        {
            get
            {
                return _insurant_phone;
            }
            set
            {
                Oninsurant_phoneChanging(value);
                ReportPropertyChanging("insurant_phone");
                _insurant_phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("insurant_phone");
                Oninsurant_phoneChanged();
            }
        }
        private global::System.String _insurant_phone;
        partial void Oninsurant_phoneChanging(global::System.String value);
        partial void Oninsurant_phoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> accident_time
        {
            get
            {
                return _accident_time;
            }
            set
            {
                Onaccident_timeChanging(value);
                ReportPropertyChanging("accident_time");
                _accident_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("accident_time");
                Onaccident_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _accident_time;
        partial void Onaccident_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onaccident_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String accident_reason
        {
            get
            {
                return _accident_reason;
            }
            set
            {
                Onaccident_reasonChanging(value);
                ReportPropertyChanging("accident_reason");
                _accident_reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("accident_reason");
                Onaccident_reasonChanged();
            }
        }
        private global::System.String _accident_reason;
        partial void Onaccident_reasonChanging(global::System.String value);
        partial void Onaccident_reasonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String accident_area
        {
            get
            {
                return _accident_area;
            }
            set
            {
                Onaccident_areaChanging(value);
                ReportPropertyChanging("accident_area");
                _accident_area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("accident_area");
                Onaccident_areaChanged();
            }
        }
        private global::System.String _accident_area;
        partial void Onaccident_areaChanging(global::System.String value);
        partial void Onaccident_areaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String accident_address
        {
            get
            {
                return _accident_address;
            }
            set
            {
                Onaccident_addressChanging(value);
                ReportPropertyChanging("accident_address");
                _accident_address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("accident_address");
                Onaccident_addressChanged();
            }
        }
        private global::System.String _accident_address;
        partial void Onaccident_addressChanging(global::System.String value);
        partial void Onaccident_addressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String accident_details
        {
            get
            {
                return _accident_details;
            }
            set
            {
                Onaccident_detailsChanging(value);
                ReportPropertyChanging("accident_details");
                _accident_details = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("accident_details");
                Onaccident_detailsChanged();
            }
        }
        private global::System.String _accident_details;
        partial void Onaccident_detailsChanging(global::System.String value);
        partial void Onaccident_detailsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hospital_name
        {
            get
            {
                return _hospital_name;
            }
            set
            {
                Onhospital_nameChanging(value);
                ReportPropertyChanging("hospital_name");
                _hospital_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hospital_name");
                Onhospital_nameChanged();
            }
        }
        private global::System.String _hospital_name;
        partial void Onhospital_nameChanging(global::System.String value);
        partial void Onhospital_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hospital_type
        {
            get
            {
                return _hospital_type;
            }
            set
            {
                Onhospital_typeChanging(value);
                ReportPropertyChanging("hospital_type");
                _hospital_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hospital_type");
                Onhospital_typeChanged();
            }
        }
        private global::System.String _hospital_type;
        partial void Onhospital_typeChanging(global::System.String value);
        partial void Onhospital_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hospital_days
        {
            get
            {
                return _hospital_days;
            }
            set
            {
                Onhospital_daysChanging(value);
                ReportPropertyChanging("hospital_days");
                _hospital_days = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hospital_days");
                Onhospital_daysChanged();
            }
        }
        private Nullable<global::System.Int32> _hospital_days;
        partial void Onhospital_daysChanging(Nullable<global::System.Int32> value);
        partial void Onhospital_daysChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hospital_is_two_public
        {
            get
            {
                return _hospital_is_two_public;
            }
            set
            {
                Onhospital_is_two_publicChanging(value);
                ReportPropertyChanging("hospital_is_two_public");
                _hospital_is_two_public = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hospital_is_two_public");
                Onhospital_is_two_publicChanged();
            }
        }
        private Nullable<global::System.Int32> _hospital_is_two_public;
        partial void Onhospital_is_two_publicChanging(Nullable<global::System.Int32> value);
        partial void Onhospital_is_two_publicChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transfer_bank
        {
            get
            {
                return _transfer_bank;
            }
            set
            {
                Ontransfer_bankChanging(value);
                ReportPropertyChanging("transfer_bank");
                _transfer_bank = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transfer_bank");
                Ontransfer_bankChanged();
            }
        }
        private global::System.String _transfer_bank;
        partial void Ontransfer_bankChanging(global::System.String value);
        partial void Ontransfer_bankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transfer_name
        {
            get
            {
                return _transfer_name;
            }
            set
            {
                Ontransfer_nameChanging(value);
                ReportPropertyChanging("transfer_name");
                _transfer_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transfer_name");
                Ontransfer_nameChanged();
            }
        }
        private global::System.String _transfer_name;
        partial void Ontransfer_nameChanging(global::System.String value);
        partial void Ontransfer_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transfer_account
        {
            get
            {
                return _transfer_account;
            }
            set
            {
                Ontransfer_accountChanging(value);
                ReportPropertyChanging("transfer_account");
                _transfer_account = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transfer_account");
                Ontransfer_accountChanged();
            }
        }
        private global::System.String _transfer_account;
        partial void Ontransfer_accountChanging(global::System.String value);
        partial void Ontransfer_accountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String compensation_type
        {
            get
            {
                return _compensation_type;
            }
            set
            {
                Oncompensation_typeChanging(value);
                ReportPropertyChanging("compensation_type");
                _compensation_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("compensation_type");
                Oncompensation_typeChanged();
            }
        }
        private global::System.String _compensation_type;
        partial void Oncompensation_typeChanging(global::System.String value);
        partial void Oncompensation_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> compensation_amount
        {
            get
            {
                return _compensation_amount;
            }
            set
            {
                Oncompensation_amountChanging(value);
                ReportPropertyChanging("compensation_amount");
                _compensation_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("compensation_amount");
                Oncompensation_amountChanged();
            }
        }
        private Nullable<global::System.Double> _compensation_amount;
        partial void Oncompensation_amountChanging(Nullable<global::System.Double> value);
        partial void Oncompensation_amountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String admissibility_type
        {
            get
            {
                return _admissibility_type;
            }
            set
            {
                Onadmissibility_typeChanging(value);
                ReportPropertyChanging("admissibility_type");
                _admissibility_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("admissibility_type");
                Onadmissibility_typeChanged();
            }
        }
        private global::System.String _admissibility_type;
        partial void Onadmissibility_typeChanging(global::System.String value);
        partial void Onadmissibility_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String subtract_type
        {
            get
            {
                return _subtract_type;
            }
            set
            {
                Onsubtract_typeChanging(value);
                ReportPropertyChanging("subtract_type");
                _subtract_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("subtract_type");
                Onsubtract_typeChanged();
            }
        }
        private global::System.String _subtract_type;
        partial void Onsubtract_typeChanging(global::System.String value);
        partial void Onsubtract_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> subtract_amount
        {
            get
            {
                return _subtract_amount;
            }
            set
            {
                Onsubtract_amountChanging(value);
                ReportPropertyChanging("subtract_amount");
                _subtract_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("subtract_amount");
                Onsubtract_amountChanged();
            }
        }
        private Nullable<global::System.Double> _subtract_amount;
        partial void Onsubtract_amountChanging(Nullable<global::System.Double> value);
        partial void Onsubtract_amountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> invoice_amount
        {
            get
            {
                return _invoice_amount;
            }
            set
            {
                Oninvoice_amountChanging(value);
                ReportPropertyChanging("invoice_amount");
                _invoice_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("invoice_amount");
                Oninvoice_amountChanged();
            }
        }
        private Nullable<global::System.Double> _invoice_amount;
        partial void Oninvoice_amountChanging(Nullable<global::System.Double> value);
        partial void Oninvoice_amountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> deductible_amount
        {
            get
            {
                return _deductible_amount;
            }
            set
            {
                Ondeductible_amountChanging(value);
                ReportPropertyChanging("deductible_amount");
                _deductible_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deductible_amount");
                Ondeductible_amountChanged();
            }
        }
        private Nullable<global::System.Double> _deductible_amount;
        partial void Ondeductible_amountChanging(Nullable<global::System.Double> value);
        partial void Ondeductible_amountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adjustment_remark
        {
            get
            {
                return _adjustment_remark;
            }
            set
            {
                Onadjustment_remarkChanging(value);
                ReportPropertyChanging("adjustment_remark");
                _adjustment_remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adjustment_remark");
                Onadjustment_remarkChanged();
            }
        }
        private global::System.String _adjustment_remark;
        partial void Onadjustment_remarkChanging(global::System.String value);
        partial void Onadjustment_remarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_need_communication
        {
            get
            {
                return _is_need_communication;
            }
            set
            {
                Onis_need_communicationChanging(value);
                ReportPropertyChanging("is_need_communication");
                _is_need_communication = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_need_communication");
                Onis_need_communicationChanged();
            }
        }
        private Nullable<global::System.Int32> _is_need_communication;
        partial void Onis_need_communicationChanging(Nullable<global::System.Int32> value);
        partial void Onis_need_communicationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String communication_content
        {
            get
            {
                return _communication_content;
            }
            set
            {
                Oncommunication_contentChanging(value);
                ReportPropertyChanging("communication_content");
                _communication_content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("communication_content");
                Oncommunication_contentChanged();
            }
        }
        private global::System.String _communication_content;
        partial void Oncommunication_contentChanging(global::System.String value);
        partial void Oncommunication_contentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> communication_result
        {
            get
            {
                return _communication_result;
            }
            set
            {
                Oncommunication_resultChanging(value);
                ReportPropertyChanging("communication_result");
                _communication_result = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("communication_result");
                Oncommunication_resultChanged();
            }
        }
        private Nullable<global::System.Int32> _communication_result;
        partial void Oncommunication_resultChanging(Nullable<global::System.Int32> value);
        partial void Oncommunication_resultChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String check_result
        {
            get
            {
                return _check_result;
            }
            set
            {
                Oncheck_resultChanging(value);
                ReportPropertyChanging("check_result");
                _check_result = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("check_result");
                Oncheck_resultChanged();
            }
        }
        private global::System.String _check_result;
        partial void Oncheck_resultChanging(global::System.String value);
        partial void Oncheck_resultChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String check_opinion
        {
            get
            {
                return _check_opinion;
            }
            set
            {
                Oncheck_opinionChanging(value);
                ReportPropertyChanging("check_opinion");
                _check_opinion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("check_opinion");
                Oncheck_opinionChanged();
            }
        }
        private global::System.String _check_opinion;
        partial void Oncheck_opinionChanging(global::System.String value);
        partial void Oncheck_opinionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String check_subtract_type
        {
            get
            {
                return _check_subtract_type;
            }
            set
            {
                Oncheck_subtract_typeChanging(value);
                ReportPropertyChanging("check_subtract_type");
                _check_subtract_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("check_subtract_type");
                Oncheck_subtract_typeChanged();
            }
        }
        private global::System.String _check_subtract_type;
        partial void Oncheck_subtract_typeChanging(global::System.String value);
        partial void Oncheck_subtract_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> check_subtract_amount
        {
            get
            {
                return _check_subtract_amount;
            }
            set
            {
                Oncheck_subtract_amountChanging(value);
                ReportPropertyChanging("check_subtract_amount");
                _check_subtract_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("check_subtract_amount");
                Oncheck_subtract_amountChanged();
            }
        }
        private Nullable<global::System.Double> _check_subtract_amount;
        partial void Oncheck_subtract_amountChanging(Nullable<global::System.Double> value);
        partial void Oncheck_subtract_amountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String check_subtract_content
        {
            get
            {
                return _check_subtract_content;
            }
            set
            {
                Oncheck_subtract_contentChanging(value);
                ReportPropertyChanging("check_subtract_content");
                _check_subtract_content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("check_subtract_content");
                Oncheck_subtract_contentChanged();
            }
        }
        private global::System.String _check_subtract_content;
        partial void Oncheck_subtract_contentChanging(global::System.String value);
        partial void Oncheck_subtract_contentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rejected_type
        {
            get
            {
                return _rejected_type;
            }
            set
            {
                Onrejected_typeChanging(value);
                ReportPropertyChanging("rejected_type");
                _rejected_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rejected_type");
                Onrejected_typeChanged();
            }
        }
        private global::System.String _rejected_type;
        partial void Onrejected_typeChanging(global::System.String value);
        partial void Onrejected_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rejected_nature
        {
            get
            {
                return _rejected_nature;
            }
            set
            {
                Onrejected_natureChanging(value);
                ReportPropertyChanging("rejected_nature");
                _rejected_nature = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rejected_nature");
                Onrejected_natureChanged();
            }
        }
        private global::System.String _rejected_nature;
        partial void Onrejected_natureChanging(global::System.String value);
        partial void Onrejected_natureChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> rejected_amount
        {
            get
            {
                return _rejected_amount;
            }
            set
            {
                Onrejected_amountChanging(value);
                ReportPropertyChanging("rejected_amount");
                _rejected_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rejected_amount");
                Onrejected_amountChanged();
            }
        }
        private Nullable<global::System.Double> _rejected_amount;
        partial void Onrejected_amountChanging(Nullable<global::System.Double> value);
        partial void Onrejected_amountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rejected_reason
        {
            get
            {
                return _rejected_reason;
            }
            set
            {
                Onrejected_reasonChanging(value);
                ReportPropertyChanging("rejected_reason");
                _rejected_reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rejected_reason");
                Onrejected_reasonChanged();
            }
        }
        private global::System.String _rejected_reason;
        partial void Onrejected_reasonChanging(global::System.String value);
        partial void Onrejected_reasonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String approval_result
        {
            get
            {
                return _approval_result;
            }
            set
            {
                Onapproval_resultChanging(value);
                ReportPropertyChanging("approval_result");
                _approval_result = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("approval_result");
                Onapproval_resultChanged();
            }
        }
        private global::System.String _approval_result;
        partial void Onapproval_resultChanging(global::System.String value);
        partial void Onapproval_resultChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String report_user
        {
            get
            {
                return _report_user;
            }
            set
            {
                Onreport_userChanging(value);
                ReportPropertyChanging("report_user");
                _report_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("report_user");
                Onreport_userChanged();
            }
        }
        private global::System.String _report_user;
        partial void Onreport_userChanging(global::System.String value);
        partial void Onreport_userChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> report_submit_time
        {
            get
            {
                return _report_submit_time;
            }
            set
            {
                Onreport_submit_timeChanging(value);
                ReportPropertyChanging("report_submit_time");
                _report_submit_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("report_submit_time");
                Onreport_submit_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _report_submit_time;
        partial void Onreport_submit_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onreport_submit_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String record_user
        {
            get
            {
                return _record_user;
            }
            set
            {
                Onrecord_userChanging(value);
                ReportPropertyChanging("record_user");
                _record_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("record_user");
                Onrecord_userChanged();
            }
        }
        private global::System.String _record_user;
        partial void Onrecord_userChanging(global::System.String value);
        partial void Onrecord_userChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> record_submit_time
        {
            get
            {
                return _record_submit_time;
            }
            set
            {
                Onrecord_submit_timeChanging(value);
                ReportPropertyChanging("record_submit_time");
                _record_submit_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("record_submit_time");
                Onrecord_submit_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _record_submit_time;
        partial void Onrecord_submit_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onrecord_submit_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adjust_user
        {
            get
            {
                return _adjust_user;
            }
            set
            {
                Onadjust_userChanging(value);
                ReportPropertyChanging("adjust_user");
                _adjust_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adjust_user");
                Onadjust_userChanged();
            }
        }
        private global::System.String _adjust_user;
        partial void Onadjust_userChanging(global::System.String value);
        partial void Onadjust_userChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> adjust_submit_time
        {
            get
            {
                return _adjust_submit_time;
            }
            set
            {
                Onadjust_submit_timeChanging(value);
                ReportPropertyChanging("adjust_submit_time");
                _adjust_submit_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adjust_submit_time");
                Onadjust_submit_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _adjust_submit_time;
        partial void Onadjust_submit_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onadjust_submit_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String check_user
        {
            get
            {
                return _check_user;
            }
            set
            {
                Oncheck_userChanging(value);
                ReportPropertyChanging("check_user");
                _check_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("check_user");
                Oncheck_userChanged();
            }
        }
        private global::System.String _check_user;
        partial void Oncheck_userChanging(global::System.String value);
        partial void Oncheck_userChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> check_submit_time
        {
            get
            {
                return _check_submit_time;
            }
            set
            {
                Oncheck_submit_timeChanging(value);
                ReportPropertyChanging("check_submit_time");
                _check_submit_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("check_submit_time");
                Oncheck_submit_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _check_submit_time;
        partial void Oncheck_submit_timeChanging(Nullable<global::System.DateTime> value);
        partial void Oncheck_submit_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String approval_user
        {
            get
            {
                return _approval_user;
            }
            set
            {
                Onapproval_userChanging(value);
                ReportPropertyChanging("approval_user");
                _approval_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("approval_user");
                Onapproval_userChanged();
            }
        }
        private global::System.String _approval_user;
        partial void Onapproval_userChanging(global::System.String value);
        partial void Onapproval_userChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> approval_submit_time
        {
            get
            {
                return _approval_submit_time;
            }
            set
            {
                Onapproval_submit_timeChanging(value);
                ReportPropertyChanging("approval_submit_time");
                _approval_submit_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("approval_submit_time");
                Onapproval_submit_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _approval_submit_time;
        partial void Onapproval_submit_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onapproval_submit_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> allowance_amount
        {
            get
            {
                return _allowance_amount;
            }
            set
            {
                Onallowance_amountChanging(value);
                ReportPropertyChanging("allowance_amount");
                _allowance_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowance_amount");
                Onallowance_amountChanged();
            }
        }
        private Nullable<global::System.Double> _allowance_amount;
        partial void Onallowance_amountChanging(Nullable<global::System.Double> value);
        partial void Onallowance_amountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String case_source
        {
            get
            {
                return _case_source;
            }
            set
            {
                Oncase_sourceChanging(value);
                ReportPropertyChanging("case_source");
                _case_source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("case_source");
                Oncase_sourceChanged();
            }
        }
        private global::System.String _case_source;
        partial void Oncase_sourceChanging(global::System.String value);
        partial void Oncase_sourceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> expire_date
        {
            get
            {
                return _expire_date;
            }
            set
            {
                Onexpire_dateChanging(value);
                ReportPropertyChanging("expire_date");
                _expire_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("expire_date");
                Onexpire_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _expire_date;
        partial void Onexpire_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onexpire_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String case_type
        {
            get
            {
                return _case_type;
            }
            set
            {
                Oncase_typeChanging(value);
                ReportPropertyChanging("case_type");
                _case_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("case_type");
                Oncase_typeChanged();
            }
        }
        private global::System.String _case_type;
        partial void Oncase_typeChanging(global::System.String value);
        partial void Oncase_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String case_type_remark
        {
            get
            {
                return _case_type_remark;
            }
            set
            {
                Oncase_type_remarkChanging(value);
                ReportPropertyChanging("case_type_remark");
                _case_type_remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("case_type_remark");
                Oncase_type_remarkChanged();
            }
        }
        private global::System.String _case_type_remark;
        partial void Oncase_type_remarkChanging(global::System.String value);
        partial void Oncase_type_remarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String subtract_type_remark
        {
            get
            {
                return _subtract_type_remark;
            }
            set
            {
                Onsubtract_type_remarkChanging(value);
                ReportPropertyChanging("subtract_type_remark");
                _subtract_type_remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("subtract_type_remark");
                Onsubtract_type_remarkChanged();
            }
        }
        private global::System.String _subtract_type_remark;
        partial void Onsubtract_type_remarkChanging(global::System.String value);
        partial void Onsubtract_type_remarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="B_Models", Name="field_range")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class field_range : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 field_range 对象。
        /// </summary>
        /// <param name="fid">fid 属性的初始值。</param>
        public static field_range Createfield_range(global::System.Int32 fid)
        {
            field_range field_range = new field_range();
            field_range.fid = fid;
            return field_range;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fid
        {
            get
            {
                return _fid;
            }
            set
            {
                if (_fid != value)
                {
                    OnfidChanging(value);
                    ReportPropertyChanging("fid");
                    _fid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fid");
                    OnfidChanged();
                }
            }
        }
        private global::System.Int32 _fid;
        partial void OnfidChanging(global::System.Int32 value);
        partial void OnfidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String field_name
        {
            get
            {
                return _field_name;
            }
            set
            {
                Onfield_nameChanging(value);
                ReportPropertyChanging("field_name");
                _field_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("field_name");
                Onfield_nameChanged();
            }
        }
        private global::System.String _field_name;
        partial void Onfield_nameChanging(global::System.String value);
        partial void Onfield_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String field_value
        {
            get
            {
                return _field_value;
            }
            set
            {
                Onfield_valueChanging(value);
                ReportPropertyChanging("field_value");
                _field_value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("field_value");
                Onfield_valueChanged();
            }
        }
        private global::System.String _field_value;
        partial void Onfield_valueChanging(global::System.String value);
        partial void Onfield_valueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="B_Models", Name="investigation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class investigation : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 investigation 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="cid">cid 属性的初始值。</param>
        public static investigation Createinvestigation(global::System.Int32 id, global::System.String cid)
        {
            investigation investigation = new investigation();
            investigation.id = id;
            investigation.cid = cid;
            return investigation;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cid
        {
            get
            {
                return _cid;
            }
            set
            {
                OncidChanging(value);
                ReportPropertyChanging("cid");
                _cid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cid");
                OncidChanged();
            }
        }
        private global::System.String _cid;
        partial void OncidChanging(global::System.String value);
        partial void OncidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String investigation_cause
        {
            get
            {
                return _investigation_cause;
            }
            set
            {
                Oninvestigation_causeChanging(value);
                ReportPropertyChanging("investigation_cause");
                _investigation_cause = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("investigation_cause");
                Oninvestigation_causeChanged();
            }
        }
        private global::System.String _investigation_cause;
        partial void Oninvestigation_causeChanging(global::System.String value);
        partial void Oninvestigation_causeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String investigation_area
        {
            get
            {
                return _investigation_area;
            }
            set
            {
                Oninvestigation_areaChanging(value);
                ReportPropertyChanging("investigation_area");
                _investigation_area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("investigation_area");
                Oninvestigation_areaChanged();
            }
        }
        private global::System.String _investigation_area;
        partial void Oninvestigation_areaChanging(global::System.String value);
        partial void Oninvestigation_areaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contact
        {
            get
            {
                return _contact;
            }
            set
            {
                OncontactChanging(value);
                ReportPropertyChanging("contact");
                _contact = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contact");
                OncontactChanged();
            }
        }
        private global::System.String _contact;
        partial void OncontactChanging(global::System.String value);
        partial void OncontactChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contact_phone
        {
            get
            {
                return _contact_phone;
            }
            set
            {
                Oncontact_phoneChanging(value);
                ReportPropertyChanging("contact_phone");
                _contact_phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contact_phone");
                Oncontact_phoneChanged();
            }
        }
        private global::System.String _contact_phone;
        partial void Oncontact_phoneChanging(global::System.String value);
        partial void Oncontact_phoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String survey_points
        {
            get
            {
                return _survey_points;
            }
            set
            {
                Onsurvey_pointsChanging(value);
                ReportPropertyChanging("survey_points");
                _survey_points = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("survey_points");
                Onsurvey_pointsChanged();
            }
        }
        private global::System.String _survey_points;
        partial void Onsurvey_pointsChanging(global::System.String value);
        partial void Onsurvey_pointsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String approval_result
        {
            get
            {
                return _approval_result;
            }
            set
            {
                Onapproval_resultChanging(value);
                ReportPropertyChanging("approval_result");
                _approval_result = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("approval_result");
                Onapproval_resultChanged();
            }
        }
        private global::System.String _approval_result;
        partial void Onapproval_resultChanging(global::System.String value);
        partial void Onapproval_resultChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String approval_remark
        {
            get
            {
                return _approval_remark;
            }
            set
            {
                Onapproval_remarkChanging(value);
                ReportPropertyChanging("approval_remark");
                _approval_remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("approval_remark");
                Onapproval_remarkChanged();
            }
        }
        private global::System.String _approval_remark;
        partial void Onapproval_remarkChanging(global::System.String value);
        partial void Onapproval_remarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="B_Models", Name="lgn")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lgn : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 lgn 对象。
        /// </summary>
        /// <param name="uid">uid 属性的初始值。</param>
        /// <param name="user_name">user_name 属性的初始值。</param>
        /// <param name="password">password 属性的初始值。</param>
        /// <param name="authority_level">authority_level 属性的初始值。</param>
        public static lgn Createlgn(global::System.Int32 uid, global::System.String user_name, global::System.String password, global::System.Int32 authority_level)
        {
            lgn lgn = new lgn();
            lgn.uid = uid;
            lgn.user_name = user_name;
            lgn.password = password;
            lgn.authority_level = authority_level;
            return lgn;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 uid
        {
            get
            {
                return _uid;
            }
            set
            {
                if (_uid != value)
                {
                    OnuidChanging(value);
                    ReportPropertyChanging("uid");
                    _uid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uid");
                    OnuidChanged();
                }
            }
        }
        private global::System.Int32 _uid;
        partial void OnuidChanging(global::System.Int32 value);
        partial void OnuidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                Onuser_nameChanging(value);
                ReportPropertyChanging("user_name");
                _user_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_name");
                Onuser_nameChanged();
            }
        }
        private global::System.String _user_name;
        partial void Onuser_nameChanging(global::System.String value);
        partial void Onuser_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 authority_level
        {
            get
            {
                return _authority_level;
            }
            set
            {
                Onauthority_levelChanging(value);
                ReportPropertyChanging("authority_level");
                _authority_level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("authority_level");
                Onauthority_levelChanged();
            }
        }
        private global::System.Int32 _authority_level;
        partial void Onauthority_levelChanging(global::System.Int32 value);
        partial void Onauthority_levelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> last_login_time
        {
            get
            {
                return _last_login_time;
            }
            set
            {
                Onlast_login_timeChanging(value);
                ReportPropertyChanging("last_login_time");
                _last_login_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("last_login_time");
                Onlast_login_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _last_login_time;
        partial void Onlast_login_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onlast_login_timeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="B_Models", Name="modify_color")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class modify_color : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 modify_color 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="cid">cid 属性的初始值。</param>
        public static modify_color Createmodify_color(global::System.Int32 id, global::System.Int32 cid)
        {
            modify_color modify_color = new modify_color();
            modify_color.id = id;
            modify_color.cid = cid;
            return modify_color;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cid
        {
            get
            {
                return _cid;
            }
            set
            {
                if (_cid != value)
                {
                    OncidChanging(value);
                    ReportPropertyChanging("cid");
                    _cid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cid");
                    OncidChanged();
                }
            }
        }
        private global::System.Int32 _cid;
        partial void OncidChanging(global::System.Int32 value);
        partial void OncidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private Nullable<global::System.Int32> _state;
        partial void OnstateChanging(Nullable<global::System.Int32> value);
        partial void OnstateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String field_name
        {
            get
            {
                return _field_name;
            }
            set
            {
                Onfield_nameChanging(value);
                ReportPropertyChanging("field_name");
                _field_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("field_name");
                Onfield_nameChanged();
            }
        }
        private global::System.String _field_name;
        partial void Onfield_nameChanging(global::System.String value);
        partial void Onfield_nameChanged();

        #endregion

    
    }

    #endregion

    
}
